Insert into directors values
(1, 'Ridley Scott', 'Male', 83, 'English Film Director'),
(2, 'Joe Dante', 'Male', 74, 'Joseph James Dante, Jr. adalah sutradara, produser, editor, dan aktor film Amerika. Film-filmnya — terutama Gremlins - sering mencampurkan film-b gaya 1950-an dengan komedi kartun.'),
(3, 'Eric Goldberg', 'Male', 66, 'Eric Goldberg adalah animator Amerika, aktor suara dan sutradara film yang dikenal karena karyanya di Walt Disney Animation Studios dan Warner Bros Animation.'),
(4, 'John R. Leonetti', 'Male', 64, 'John Robert Leonetti, ASC adalah sinematografer dan sutradara film Amerika. Dia dikenal karena karya kolaboratif dengan sutradara James Wan, dengan siapa ia telah bertindak sebagai sinematografer pada lima film. Dia adalah adik dari sinematografer Matius F.'),
(5, 'Simon McQuoid', 'Male', null, 'Simon McQuoid adalah pembuat film Australia, terkenal karena mengarahkan reboot Mortal Kombat 2021. Latar belakang McQuoid adalah mengarahkan iklan.'),
(6, 'M. Night Shyamalan', 'Male', 50, 'Manoj Nelliyatu Shyamalan merupakan seorang sutradara dan aktor berkebangsaan India atau biasanya dikenal dengan M. Night Shyamalan. Dia memenangkan nominasi Academy Award. Dia dilahirkan di Mahé. Dia berkarier di dunia film sejak tahun 1992.'),
(7, 'Nicholas Meyer', 'Male', 75, 'Nicholas Meyer adalah seorang penulis dan sutradara Amerika, yang terkenal dengan novel terlarisnya The Seven-Per-Cent Solution, dan untuk mengarahkan film-film Time After Time, dua film fitur Star Trek, film televisi 1983 The Day After, dan Vendetta film asli HBO 1999.'),
(8, 'Jake Kasdan', 'Male', 46, 'Jacob "Jake" Kasdan adalah sutradara, produser, penulis skenario, dan aktor film dan televisi Amerika. Dia terkenal karena mengarahkan Bad Teacher, Sex Tape, Jumanji: Welcome to the Jungle dan Jumanji: The Next Level.'),
(9, 'Chris Columbus', 'Male', 62, 'Christopher "Chris" Columbus adalah sutradara, produser dan seorang penulis naskah yang berasal dari Amerika Serikat. Dikenal sebagai sutradara dari film francise Harry Potter, Mrs. Doubtfire dan Home Alone.'),
(10, 'Shawn Levy', 'Male', 52, 'Shawn Adam Levy (lahir di Montreal, Québec, Kanada, 23 Juli 1968; umur 52 tahun) merupakan seorang sutradara, produser dan aktor Kanada. Ia merupakan sutradara dari film Big Fat Liar, Just Married, Cheaper by the Dozen, The Pink Panther dan Night at the Museum. Ia berkarier di dunia film sejak tahun 2002.'),
(11,'Alan Taylor’,’Male’,62,’Alan Taylor (lahir sekitar tahun 1959) adalah seorang sutradara film dan televisi asal Amerika Serikat. Ia dikenal atas karyanya pada acara-acara TV seperti Lost, The West Wing, Six Feet Under, Sex and the City, The Sopranos, Game of Thrones, Boardwalk Empire, Deadwood, dan Mad Men.'),
(12,'Peter Jackson','Male',59,'Sir Peter Robert Jackson, KNZM (lahir 31 Oktober 1961; umur 59 tahun) adalah sutradara yang terutama dikenal sebagai sutradara trilogi film Lord of the Rings yang diadaptasi dari buku karya J. R. R. Tolkien. Dari trilogi film itu, Jackson menerima penghargaan dari Academy Award, Golden Globe dan BAFTA. Selain itu, Jackson juga menyutradarai film King Kong, dan District 9'),
(13,'Quentin Tarantino','Male',58,'Quentin Jerome Tarantino adalah seorang sutradara, aktor, dan penulis skenario terkenal asal Amerika Serikat.'),
(14,'George Miller','Male',76,'Dr. George Miller AO adalah sutradara film, penulis naskah, produser, dan mantan dokter medis Australia. Ia dikenal sebagai sutradara seri film Mad Max. Dua film di antaranya, The Road Warrior dan Fury Road, diakui sebagai salah satu film laga terbaik sepanjang masa,'),
(15, 'Stefano Sollima', 'Male', 55, 'Stefano Sollima was born on May 4, 1966 in Rome, Lazio, Italy. He is a director and writer, known for Tom Clancy’s Without Remorse (2021), Gomorrah (2014) and ZeroZeroZero (2019).'),
(16, 'Mamoru Hosoda', 'Male', 53, 'Mamoru Hosoda is a Japanese film director and animator. Formerly employed at Toei Animation, he went to work at Madhouse from 2005 to 2011. Hosoda left Madhouse in 2011 to establish his own animation studio, Studio Chizu.'),
(17, 'Stephen Sommers', 'Male',59, 'Stephen Sommers was born on March 20, 1962 in Indianapolis, Indiana. Raised in St. Cloud, Minnesota, he attended St. John’s University and the University of Seville in Spain. Afterward, Sommers spent the next four years performing as an actor in theater groups and managing rock bands throughout Europe.'),
(18, 'Pete Travis', 'Male',NULL, 'Pete Travis is a director and writer, known for Vantage Point (2008), Dredd (2012) and Omagh (2004).'),
(19, 'Patrick Hughes', 'Male',NULL, 'Patrick Hughes is a director and writer, known for The Hitman’s Bodyguard (2017), Red Hill (2010) and The Expendables 3 (2014).'),
(20, 'Drew Goddard', 'Male', 46, 'Drew Goddard was raised in Los Alamos, New Mexico. He attended Los Alamos High School in Los Alamos, New Mexico and graduated in 1993. He then attended the University of Colorado, and worked as a production assistant in L.A. after graduation.'),
(21, 'Martin Brest', 'Male',69, 'Martin Brest was born on August 8, 1951 in The Bronx, New York City, New York, USA. He is a director and actor, known for Scent of a Woman (1992), Midnight Run (1988) and Beverly Hills Cop (1984).');


